# -*- coding: utf-8 -*-
# Copyright (c) 2011-2013 Raphaël Barrois


BACKLIGHT_ON_NEVER = 'never'
BACKLIGHT_ON_ALWAYS = 'always'
BACKLIGHT_ON_PLAY = 'play'
BACKLIGHT_ON_PLAYPAUSE = 'playpause'
BACKLIGHT_ON_CHOICES = [BACKLIGHT_ON_ALWAYS, BACKLIGHT_ON_NEVER, BACKLIGHT_ON_PLAY, BACKLIGHT_ON_PLAYPAUSE]
